CREATE TABLE "ADMINISTRATOR".ACHIEVEMENT
(
    ACHIEVEMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
        NOT NULL PRIMARY KEY,

        USER_ID INTEGER NOT NULL, 
        ACHIEVEMENT_NAME VARCHAR(100), 
        ACHIEVEMENT_DESCRIPTION VARCHAR(255), 
        STATUS VARCHAR(20) DEFAULT 'LOCKED',
        POINTS INTEGER DEFAULT 0,
        CONSTRAINT FK_ACHIEVEMENT_USER 
        FOREIGN KEY (USER_ID) 
        REFERENCES "ADMINISTRATOR".USERS(USER_ID)
);



