
CREATE TABLE "ADMINISTRATOR".USERS
(
    USER_ID INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
        NOT NULL PRIMARY KEY,

    STUDENT_STAFF_NUMBER VARCHAR(8),
    EMAIL VARCHAR(100),
    FULL_NAME VARCHAR(80),
    CAMPUS VARCHAR(80),
    CONTACT_NUMBER VARCHAR(10),
    ROLE VARCHAR(30),
    PASSWORD_HASH VARCHAR(8),
    LANGUAGE VARCHAR(30)
);

INSERT INTO "ADMINISTRATOR".USERS (STUDENT_STAFF_NUMBER, EMAIL, FULL_NAME, CAMPUS, CONTACT_NUMBER, ROLE, PASSWORD_HASH, LANGUAGE) 
VALUES ('59876123', '59876123@mycput.ac.za', 'Thabo Molefe', 'Bellville', '5897620146', 'Student', 'Thabo', 'English'),
('89631472', '89631472@mycput.ac.za', 'Mia Roman', 'Bellville', '6974120367', 'Student', 'MiaRoman', 'English'); 
